//! Bounded SMTP email delivery for the legacy attachment endpoint.

use std::{sync::Arc, time::Duration};

use axum::{
    Router,
    extract::{Extension, Multipart},
    http::{StatusCode, header},
    response::{IntoResponse, Response},
    routing::post,
};
use lettre::{
    AsyncSmtpTransport, AsyncTransport, Message, Tokio1Executor,
    message::{Attachment, Mailbox, MultiPart, SinglePart, header::ContentType},
    transport::smtp::{
        authentication::Credentials,
        client::{Tls, TlsParameters},
    },
};
use thiserror::Error;

use crate::runtime_config::{SmtpHostnameVerification, SmtpMailConfig, SmtpTransportSecurity};

pub(crate) const SEND_EMAIL_PATH: &str = "/api/v1/general/send-email";

const MAX_ADDRESS_BYTES: usize = 320;
const MAX_SUBJECT_BYTES: usize = 4 * 1024;
const MAX_BODY_BYTES: usize = 1024 * 1024;
const MAX_FILENAME_BYTES: usize = 255;
const MAX_ATTACHMENT_BYTES: usize = 100 * 1024 * 1024;
const SMTP_TIMEOUT: Duration = Duration::from_secs(30);
const DEFAULT_SUBJECT: &str = "RustlingPDF Notification";
const DEFAULT_BODY: &str = "This message was automatically generated by RustlingPDF.<br><br>Please do not reply directly to this email.";

pub(crate) struct SmtpMailService {
    config: SmtpMailConfig,
}

struct OutgoingMail {
    recipient: Mailbox,
    subject: String,
    body: String,
    attachment: Option<MailAttachment>,
}

struct MailAttachment {
    filename: String,
    content_type: ContentType,
    bytes: Vec<u8>,
}

#[derive(Debug, Error)]
pub(crate) enum MailError {
    #[error("Invalid Addresses")]
    InvalidAddress,
    #[error("An attachment is required to send the email.")]
    MissingAttachment,
    #[error("Email request exceeds the supported size")]
    InputTooLarge,
    #[error("Email request contains invalid text")]
    InvalidText,
    #[error("SMTP configuration is incomplete")]
    InvalidConfiguration,
    #[error("Insecure SMTP certificate policy is not supported")]
    InsecureTlsPolicy,
    #[error("Could not construct the email message")]
    Message,
    #[error("SMTP delivery failed")]
    Delivery,
}

impl SmtpMailService {
    pub(crate) fn new(config: SmtpMailConfig) -> Self {
        Self { config }
    }

    async fn send(&self, outgoing: OutgoingMail) -> Result<(), MailError> {
        let message = self.build_message(outgoing)?;
        let transport = self.transport()?;
        transport
            .send(message)
            .await
            .map_err(|_| MailError::Delivery)?;
        Ok(())
    }

    fn build_message(&self, outgoing: OutgoingMail) -> Result<Message, MailError> {
        let sender = parse_mailbox(&self.config.from)?;
        let builder = Message::builder()
            .from(sender)
            .to(outgoing.recipient)
            .subject(outgoing.subject);
        let html = SinglePart::builder()
            .header(ContentType::TEXT_HTML)
            .body(outgoing.body);
        match outgoing.attachment {
            Some(attachment) => builder.multipart(
                MultiPart::mixed().singlepart(html).singlepart(
                    Attachment::new(attachment.filename)
                        .body(attachment.bytes, attachment.content_type),
                ),
            ),
            None => builder.singlepart(html),
        }
        .map_err(|_| MailError::Message)
    }

    fn transport(&self) -> Result<AsyncSmtpTransport<Tokio1Executor>, MailError> {
        let host = self.config.host.trim();
        if host.is_empty() || self.config.port == 0 {
            return Err(MailError::InvalidConfiguration);
        }
        self.validate_tls_policy(host)?;

        let mut builder = AsyncSmtpTransport::<Tokio1Executor>::builder_dangerous(host)
            .port(self.config.port)
            .timeout(Some(SMTP_TIMEOUT));
        let tls = match self.config.transport_security {
            SmtpTransportSecurity::Plaintext => None,
            SmtpTransportSecurity::OpportunisticStartTls => {
                Some(Tls::Opportunistic(tls_parameters(host)?))
            }
            SmtpTransportSecurity::RequiredStartTls => Some(Tls::Required(tls_parameters(host)?)),
            SmtpTransportSecurity::ImplicitTls => Some(Tls::Wrapper(tls_parameters(host)?)),
        };
        if let Some(tls) = tls {
            builder = builder.tls(tls);
        }
        if self.config.username.is_some() || self.config.password.is_some() {
            builder = builder.credentials(Credentials::new(
                self.config.username.clone().unwrap_or_default(),
                self.config
                    .password
                    .as_ref()
                    .map(|password| password.to_string())
                    .unwrap_or_default(),
            ));
        }
        Ok(builder.build())
    }

    fn validate_tls_policy(&self, host: &str) -> Result<(), MailError> {
        if self.config.hostname_verification == SmtpHostnameVerification::Disabled {
            return Err(MailError::InsecureTlsPolicy);
        }
        if self
            .config
            .ssl_trust
            .as_deref()
            .is_some_and(|trusted| trusted.trim() == "*" || !trusted.eq_ignore_ascii_case(host))
        {
            return Err(MailError::InsecureTlsPolicy);
        }
        Ok(())
    }
}

pub(crate) fn routes(service: Arc<SmtpMailService>) -> Router {
    Router::new()
        .route(SEND_EMAIL_PATH, post(send_email_with_attachment))
        .layer(Extension(service))
}

async fn send_email_with_attachment(
    Extension(service): Extension<Arc<SmtpMailService>>,
    multipart: Multipart,
) -> Response {
    let outgoing = match read_request(multipart).await {
        Ok(outgoing) => outgoing,
        Err(error) => return mail_error_response(&error),
    };
    match service.send(outgoing).await {
        Ok(()) => text_response(StatusCode::OK, "Email sent successfully"),
        Err(error) => mail_error_response(&error),
    }
}

async fn read_request(mut multipart: Multipart) -> Result<OutgoingMail, MailError> {
    let mut recipient = None;
    let mut subject = None;
    let mut body = None;
    let mut attachment = None;

    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|_| MailError::InvalidText)?
    {
        match field.name().unwrap_or_default() {
            "to" => recipient = Some(read_text(field, MAX_ADDRESS_BYTES).await?),
            "subject" => {
                subject = Some(read_text(field, MAX_SUBJECT_BYTES).await?);
            }
            "body" => body = Some(read_text(field, MAX_BODY_BYTES).await?),
            "fileInput" => {
                let filename = safe_attachment_filename(field.file_name())?;
                let content_type = field
                    .content_type()
                    .and_then(|value| ContentType::parse(value).ok())
                    .unwrap_or(
                        ContentType::parse("application/octet-stream")
                            .map_err(|_| MailError::Message)?,
                    );
                let bytes = field.bytes().await.map_err(|_| MailError::InvalidText)?;
                if bytes.is_empty() {
                    return Err(MailError::MissingAttachment);
                }
                if bytes.len() > MAX_ATTACHMENT_BYTES {
                    return Err(MailError::InputTooLarge);
                }
                attachment = Some(MailAttachment {
                    filename,
                    content_type,
                    bytes: bytes.to_vec(),
                });
            }
            _ => {}
        }
    }

    let recipient = recipient.ok_or(MailError::InvalidAddress)?;
    Ok(OutgoingMail {
        recipient: parse_mailbox(&recipient)?,
        subject: subject.unwrap_or_else(|| DEFAULT_SUBJECT.to_owned()),
        body: body.unwrap_or_else(|| DEFAULT_BODY.to_owned()),
        attachment: Some(attachment.ok_or(MailError::MissingAttachment)?),
    })
}

async fn read_text(
    field: axum::extract::multipart::Field<'_>,
    limit: usize,
) -> Result<String, MailError> {
    let bytes = field.bytes().await.map_err(|_| MailError::InvalidText)?;
    if bytes.len() > limit {
        return Err(MailError::InputTooLarge);
    }
    let value = String::from_utf8(bytes.to_vec()).map_err(|_| MailError::InvalidText)?;
    Ok(value)
}

fn safe_attachment_filename(filename: Option<&str>) -> Result<String, MailError> {
    let filename = filename
        .and_then(|value| value.rsplit(['/', '\\']).next())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .ok_or(MailError::MissingAttachment)?;
    if filename.len() > MAX_FILENAME_BYTES || filename.chars().any(char::is_control) {
        return Err(MailError::InvalidText);
    }
    Ok(filename.to_owned())
}

fn parse_mailbox(value: &str) -> Result<Mailbox, MailError> {
    let value = value.trim();
    if value.is_empty() || value.len() > MAX_ADDRESS_BYTES {
        return Err(MailError::InvalidAddress);
    }
    value.parse().map_err(|_| MailError::InvalidAddress)
}

fn mail_error_response(error: &MailError) -> Response {
    text_response(
        StatusCode::INTERNAL_SERVER_ERROR,
        &format!("Failed to send email: {error}"),
    )
}

fn tls_parameters(host: &str) -> Result<TlsParameters, MailError> {
    TlsParameters::new(host.to_owned()).map_err(|_| MailError::InvalidConfiguration)
}

fn text_response(status: StatusCode, text: &str) -> Response {
    (
        status,
        [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
        text.to_owned(),
    )
        .into_response()
}

#[cfg(test)]
mod tests {
    use super::{MailError, safe_attachment_filename};

    #[test]
    fn attachment_names_are_reduced_to_safe_basenames() -> Result<(), MailError> {
        assert_eq!(
            safe_attachment_filename(Some("../exports/report.pdf"))?,
            "report.pdf"
        );
        assert!(safe_attachment_filename(Some("bad\r\nname.pdf")).is_err());
        assert!(safe_attachment_filename(None).is_err());
        Ok(())
    }
}
