[ar_AR]
ignore = [
    'language.direction',
]

[az_AZ]
ignore = [
    'language.direction',
]

[bg_BG]
ignore = [
    'language.direction',
]

[bo_CN]
ignore = [
    'convert.dpi',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.summary.tech.javaScript',
    'home.devApi.title',
    'language.direction',
    'showJS.tags',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
]

[ca_CA]
ignore = [
    'language.direction',
    'watermark.type.1',
]

[cs_CZ]
ignore = [
    'language.direction',
    'text',
]

[da_DK]
ignore = [
    'language.direction',
]

[de_DE]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'adjustPageScale.pageSize.legal',
    'adjustPageScale.pageSize.letter',
    'alphabet',
    'annotation.contents',
    'annotation.polygon',
    'certSign.logoTitle',
    'certSign.name',
    'convert.dpi',
    'cookieBanner.services.posthog',
    'cookieBanner.services.scarf',
    'crop.autoCrop',
    'details',
    'fileManager.fileFormat',
    'fileManager.fileName',
    'fileManager.fileVersion',
    'fileManager.googleDrive',
    'fileManager.googleDriveShort',
    'footer.issues',
    'getPdfInfo.downloads',
    'getPdfInfo.indexTitle',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.perPage.links',
    'getPdfInfo.perPage.multimedia',
    'getPdfInfo.sections.compliance',
    'getPdfInfo.summary.tech.javaScript',
    'getPdfInfo.summary.tech.multimedia',
    'home.devApi.title',
    'language.direction',
    'legal.impressum',
    'pdfTextEditor.options.advanced.title',
    'pipeline.title',
    'pro',
    'sign.saved.type.text',
    'sign.type.text',
    'text',
    'toolPanel.alpha',
    'update.priority.normal',
    'update.version',
    'validateSignature.cert.version',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
    'validateSignature.report.downloads',
    'watermark.type.1',
    'watermark.watermarkType.text',
]

[el_GR]
ignore = [
    'language.direction',
]

[es_ES]
ignore = [
    'adjustPageScale.pageSize.legal',
    'admin.error',
    'certSign.appearance.invisible',
    'certSign.appearance.visible',
    'certSign.collab.signRequest.steps.invisible',
    'certSign.collab.signRequest.steps.visible',
    'compare.pixel.base',
    'config.overview.error',
    'convert.cbrToPdf',
    'convert.cbzToPdf',
    'convert.dpi',
    'convert.ebookToPdf',
    'convert.pdfToCbr',
    'convert.pdfToCbz',
    'convert.pdfToEpub',
    'convert.svgToPdf',
    'cookieBanner.services.posthog',
    'cookieBanner.services.scarf',
    'error._value',
    'fileManager.googleDrive',
    'fileManager.googleDriveShort',
    'footer.issues',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.perPage.multimedia',
    'getPdfInfo.summary.tech.javaScript',
    'getPdfInfo.summary.tech.multimedia',
    'home.devApi.title',
    'language.direction',
    'mobileScanner.flash',
    'no',
    'pdfTextEditor.groupingMode.auto',
    'pro',
    'redact.modeSelector.manual',
    'settings.general.title',
    'showJS.tags',
    'toolPicker.subcategories.general',
    'update.priority.normal',
    'validateSignature.cert.bits',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
]

[eu_ES]
ignore = [
    'language.direction',
]

[fa_IR]
ignore = [
    'language.direction',
]

[fr_FR]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'AddStampRequest.rotation',
    'alphabet',
    'cookieBanner.preferencesModal.serviceCounterLabel',
    'language.direction',
    'page',
    'pages',
    'pipeline.title',
    'pro',
    'showJS.tags',
    'update.version',
    'validateSignature.cert.bits',
    'validateSignature.cert.version',
    'validateSignature.date',
    'watermark.type.2',
]

[ga_IE]
ignore = [
    'convert.dpi',
    'fileManager.googleDrive',
    'footer.issues',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.summary.tech.javaScript',
    'home.devApi.title',
    'language.direction',
    'legal.impressum',
    'pro',
    'showJS.tags',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
]

[hi_IN]
ignore = [
    'language.direction',
]

[hr_HR]
ignore = [
    'language.direction',
    'showJS.tags',
]

[hu_HU]
ignore = [
    'language.direction',
    'pro',
    'showJS.tags',
]

[id_ID]
ignore = [
    'language.direction',
]

[it_IT]
ignore = [
    'language.direction',
    'no',
    'password',
    'pipeline.title',
    'showJS.tags',
]

[ja_JP]
ignore = [
    'language.direction',
]

[ko_KR]
ignore = [
    'language.direction',
]

[ml_IN]
ignore = [
    'language.direction',
]

[ml_ML]
ignore = [
    'language.direction',
]

[nl_NL]
ignore = [
    'language.direction',
]

[no_NB]
ignore = [
    'info',
    'language.direction',
]

[pk_sk]
ignore = [
    'language.direction',
]

[pl_PL]
ignore = [
    'language.direction',
]

[pt_BR]
ignore = [
    'language.direction',
]

[pt_PT]
ignore = [
    'language.direction',
    'pro',
    'update.priority.normal',
]

[ro_RO]
ignore = [
    'language.direction',
]

[ru_RU]
ignore = [
    'language.direction',
]

[sk_SK]
ignore = [
    'language.direction',
    'text',
    'watermark.type.1',
]

[sl_SI]
ignore = [
    'language.direction',
]

[sr_LATN_RS]
ignore = [
    'font',
    'language.direction',
    'pro',
    'showJS.tags',
]

[sv_SE]
ignore = [
    'language.direction',
]

[th_TH]
ignore = [
    'language.direction',
    'showJS.tags',
]

[tr_TR]
ignore = [
    'language.direction',
]

[uk_UA]
ignore = [
    'language.direction',
]

[vi_VN]
ignore = [
    'language.direction',
    'showJS.tags',
]

[zh_BO]
ignore = [
    'language.direction',
]

[zh_CN]
ignore = [
    'language.direction',
]

[zh_TW]
ignore = [
    'convert.cbrToPdf',
    'convert.cbzToPdf',
    'convert.dpi',
    'convert.ebookToPdf',
    'convert.emlToPdf',
    'convert.pdfToCbr',
    'convert.pdfToCbz',
    'convert.pdfToEpub',
    'convert.svgToPdf',
    'fileManager.googleDrive',
    'footer.issues',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.summary.tech.javaScript',
    'home.devApi.title',
    'language.direction',
    'showJS.tags',
    'toolPanel.alpha',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
]
