export interface AppConfig {
  baseUrl?: string;
  contextPath?: string;
  serverPort?: number;
  frontendUrl?: string;
  appNameNavbar?: string;
  languages?: string[];
  defaultLocale?: string;
  logoStyle?: "modern" | "classic";
  enableAlphaFunctionality?: boolean;
  enableDesktopInstallSlide?: boolean;
  termsAndConditions?: string;
  privacyPolicy?: string;
  cookiePolicy?: string;
  impressum?: string;
  accessibilityStatement?: string;
  serverCertificateEnabled?: boolean;
  hardwareSigningAvailable?: boolean;
  enableMobileScanner?: boolean;
  mobileScannerConvertToPdf?: boolean;
  mobileScannerImageResolution?: string;
  mobileScannerPageFormat?: string;
  mobileScannerStretchToFit?: boolean;
  appVersion?: string;
  machineType?: string;
  dependenciesReady?: boolean;
  error?: string;
  defaultHideUnavailableTools?: boolean;
  defaultHideUnavailableConversions?: boolean;
  hideDisabledToolsGoogleDrive?: boolean;
  hideDisabledToolsMobileQRScanner?: boolean;
  googleDriveEnabled?: boolean;
  googleDriveClientId?: string;
  googleDriveApiKey?: string;
  googleDriveAppId?: string;
  timestampDefaultTsaUrl?: string;
  timestampCustomTsaUrls?: string[];
  timestampTsaPresets?: { label: string; url: string }[];
  aiEngineEnabled?: boolean;
}

export type AppConfigBootstrapMode = "blocking" | "non-blocking";
